apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx
  namespace: {{ .Values.global.namespace}}
spec:
  rules:
  - host: {{ .Values.ingress.host}}
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
